#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

[ "$1" == "" ] && show_usage "uninstall-list-file"

APKs=$1

log "Processing APKs in $APKs"

while read -r line; do
  log "Uninstalling $line";
  # redirect the input otherwise main file will be read by adb
  adb shell pm uninstall -k --user 0 $line < /dev/null
done < "$APKs"
