#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

BACKUP_ROOT_FOLDER="/tmp"

[ "$#" -ne 2 ] && show_usage "volume-name file-path"

backup_volume $1 $2
