#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

[ "$1" == "" ] && show_usage "image-name | all"
check_env "GITHUB_REPO DOCKER_HUB_USER IMAGE_PREFIX IMAGE_PLATFORMS"

function build_docker_hub_image() {
 local short_name=$1
 buildx_image_from_github "$GITHUB_REPO" "$IMAGE_PREFIX" "$short_name" \
   "$IMAGE_PLATFORMS" "$DOCKER_HUB_USER"
}

function build_all() {
 check_env "IMAGE_LIST"
 for image in ${IMAGE_LIST[*]}; do
  build_docker_hub_image "$image"
 done
}

case $1 in
 all)
  build_all
  ;;
 *)
  build_docker_hub_image $1
  ;;
esac

# clean up builder container
BUILDER_CONTAINER="buildx_buildkit_multi-platform-builder0"
delete_container $BUILDER_CONTAINER
