#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

[ "$1" == "" ] && show_usage "image-name | all"

check_packages "curl jq"

function build_docker_hub_image() {
 local image_name=$1
 local trigger_name="trigger_$image_name"

 check_env "$trigger_name"
 local trigger_url="https://hub.docker.com/api/build/v1/source/${!trigger_name}/call/"

 log "Starting Docker Hub build: $image_name"
 local state=$(curl --silent -X POST "$trigger_url" | jq '.state')
 log $state
}

function build_all() {
 build_docker_hub_image alpine
 build_docker_hub_image python3
 build_docker_hub_image nook-weather
 build_docker_hub_image mqtt
 build_docker_hub_image samba
}

case $1 in
 all)
  build_all
  ;;
 *)
  build_docker_hub_image $1
  ;;
esac
