#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

[ "$#" != "2" ] && show_usage "container_name memory_percentage"

CONTAINER=$1
THRESHOLD=$2

restart_container $CONTAINER $THRESHOLD
