#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "SFTP_USER SFTP_PASSWORD SFTP_PORT CONTAINER_UID"

CONTAINER="sftp"
IMAGE="atmoz/sftp:alpine"

ROOT_FOLDER="/download/sftp"

USER_CONF="/tmp/atmos-sftp.conf"
echo "$SFTP_USER:$SFTP_PASSWORD:$CONTAINER_UID:$CONTAINER_UID:share" > $USER_CONF

SSH_KEY=$CONTAINER_CONFIG_ROOT/sftp/ssh_host_ed25519_key
if [ ! -e $SSH_KEY ]; then
 debug "Generating SFTP key: $SSH_KEY"
 sudo ssh-keygen -t ed25519 -f $SSH_KEY < /dev/null
fi

MAX_RAM="100m"
EXTRA_OPTS=(
 -v $USER_CONF:/etc/sftp/users.conf:ro
 -v $SSH_KEY:/etc/ssh/ssh_host_ed25519_key:ro
 -v $ROOT_FOLDER:/home/$SFTP_USER/share
 -p $SFTP_PORT:22
 -p $SFTP_PORT:8388/udp
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
