#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "CONTAINER_CONFIG_ROOT"

CONTAINER="hass"
IMAGE="ghcr.io/home-assistant/home-assistant:stable"

HOST_PATH=$CONTAINER_CONFIG_ROOT/$CONTAINER
grant_container_access $HOST_PATH $CERT_STORAGE

MAX_RAM="1024m"
EXTRA_OPTS=(
 --log-driver none
 --cap-drop ALL
 --security-opt no-new-privileges
 -p 14104:8123
 -v $HOST_PATH/config:/config
 -v $HOST_PATH/bin:/cmd:ro
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
# Home Assistant uses customized init
NO_DOCKER_INIT="yes"
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
