#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "CONTAINER_CONFIG_ROOT HASS_PORT_LOCAL"

CONTAINER="hass"
IMAGE="ghcr.io/home-assistant/home-assistant:stable"

HOST_PATH=$CONTAINER_CONFIG_ROOT/$CONTAINER
grant_container_access $HOST_PATH $CERT_STORAGE

MAX_RAM="1024m"
EXTRA_OPTS=(
 --log-driver none
 --cap-drop ALL
 --security-opt no-new-privileges
 -p $HASS_PORT_LOCAL:8123
 -v $HOST_PATH/config:/config
 -v $HOST_PATH/bin:/cmd:ro
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
# Home Assistant uses customized init
NO_DOCKER_INIT="yes"
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

if [ "$HASS_DOMAIN" != "" ]; then
 debug "Starting nginx reverse proxy with external domain ($HASS_DOMAIN)..."
 nginx proxy $HASS_DOMAIN $HASS_PORT_LOCAL
elif [ "$HASS_PORT_EXT" != "" ]; then
 debug "Starting nginx reverse proxy..."
 nginx $CONTAINER $HASS_PORT_EXT $HASS_PORT_LOCAL
fi
