#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "CONTAINER_CONFIG_ROOT CERT_STORAGE CONTAINER_UID"

CONTAINER="hass"
IMAGE="gadget1999/rpi-homeassistant"

HOST_PATH=$CONTAINER_CONFIG_ROOT/$CONTAINER
grant_container_access $HOST_PATH $CERT_STORAGE

MAX_RAM="100m"
EXTRA_OPTS=(
 --log-driver none
 -p 14104:8123
 -v $HOST_PATH/config:/config/homeassistant:ro
 -v $HOST_PATH/bin:/cmd:ro
 -v $CERT_STORAGE:/config/letsencrypt
 -u $CONTAINER_UID
 -m $MAX_RAM
 )

ENTRYPOINT=(
 hass -c /config/homeassistant
   --log-file /tmp/hass.log
 )

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
