#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

[ "$1" == "" ] && show_usage "http-port"

IMAGE="jmalloc/echo-server"

EXTRA_OPTS=(
 -p $1:8080
)

ENTRYPOINT=()

container_cli $IMAGE EXTRA_OPTS ENTRYPOINT
