#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="influxdb"
IMAGE="influxdb:alpine"

check_env "CONTAINER CONTAINER_CONFIG_ROOT"

INFLUXDB_ROOT=$CONTAINER_CONFIG_ROOT/$CONTAINER
INFLUXDB_PORT=15636

function prepare_container_folders() {
 local container_root=$1
 local -n subfolders=$2 # use an array to avoid space/quote issues  

 if [ ! -d $container_root ]; then
  debug "Creating folder: $container_root"
  sudo mkdir -p $container_root
  grant_container_access $container_root
 fi

 for subfolder in "${subfolders[@]}"; do
  local folder=$container_root/$subfolder
  if [ ! -d $folder ]; then
   debug "Creating folder: $folder"
   sudo mkdir -p $folder
   grant_container_access $folder
  fi
 done 
}

prepare_container_folders $INFLUXDB_ROOT (data config)

#########################
# Helper functions
#########################

function setup_influxdb() {
 check_env "DOCKER_INFLUXDB_USER DOCKER_INFLUXDB_PWD DOCKER_INFLUXDB_ORG"
 EXTRA_OPTS=(
  -p $INFLUXDB_PORT:8086
  -v $INFLUXDB_ROOT/data:/var/lib/influxdb2
  -v $INFLUXDB_ROOT/config:/etc/influxdb2
  -e DOCKER_INFLUXDB_INIT_MODE=setup
  -e DOCKER_INFLUXDB_INIT_USERNAME=$DOCKER_INFLUXDB_USER
  -e DOCKER_INFLUXDB_INIT_PASSWORD=$DOCKER_INFLUXDB_PWD
  -e DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_ORG
  -e DOCKER_INFLUXDB_INIT_BUCKET=init-bucket
  )

 ENTRYPOINT=()

 container_cli $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
}

function run_influxdb() {
 EXTRA_OPTS=(
  -p $INFLUXDB_PORT:8086
  -v $INFLUXDB_ROOT/data:/var/lib/influxdb2
  -v $INFLUXDB_ROOT/config:/etc/influxdb2
  )

 ENTRYPOINT=()

 new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
}

#########################
# Main entrance
#########################

case $1 in
 setup)
  setup_influxdb
  ;;
 debug)
  DEBUG_DOCKER=1
  run_influxdb
  ;;
 *)
  run_influxdb
  ;;
esac
