#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/email.sh
source $CMD_PATH/lib/docker.sh
source $CMD_PATH/lib/certificate.sh

check_cert_env
check_env "CERT_STORAGE CERT_ROOT"
[ "$1" == "force" ] && FORCE="--force"

if [ "$ENABLE_JIT_ACCESS" != "" ]; then
 log "Enable firewall JIT access"
 $CMD_PATH/$ENABLE_JIT_ACCESS
fi

log "Begin to issue certificate: $DDNS_DOMAIN"
if ! issue_certificate_docker $FORCE; then
 log_error "Certificate was not issued."
 exit
fi

if [ "$MAIN_EMAIL" != "" ]; then
 log "Sending email notification to $MAIN_EMAIL"
 check_email_env
 send_email \
  $MAIN_EMAIL \
  "$DDNS_DOMAIN certificate was issued successfully" \
  "Enjoy!"
fi

FULLCHAIN_FILENAME="$DDNS_DOMAIN.fullchain.pem"
KEY_FILENAME="$DDNS_DOMAIN.privkey.pem"
log "Copying $CERT_ROOT/$CERT_FULLCHAIN to $CERT_STORAGE/$FULLCHAIN_FILENAME"
copy_file "$CERT_ROOT/$CERT_FULLCHAIN" "$CERT_STORAGE/$FULLCHAIN_FILENAME" overwrite
log "Copying $CERT_ROOT/$CERT_KEY to $CERT_STORAGE/$KEY_FILENAME"
copy_file "$CERT_ROOT/$CERT_KEY" "$CERT_STORAGE/$KEY_FILENAME" overwrite
grant_container_access "$CERT_STORAGE/*"
sudo chmod 600 $CERT_STORAGE/*
ls -l $CERT_STORAGE
