#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="kali"
IMAGE="gadget1999/rpi-kali"

echo "Stop current container"
stop_container $CONTAINER

EXTRA_OPTS=(
 -v $CONTAINER-root:/root
 -v $CONTAINER-postgres:/var/lib/postgresql
 -u $MAIN_USER_ID
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
