#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "CONTAINER_CONFIG_ROOT CERT_STORAGE CONTAINER_UID"

CONTAINER="mqtt"
IMAGE="gadget1999/rpi-mqtt"

grant_container_access $CONTAINER_CONFIG_ROOT/$CONTAINER $CERT_STORAGE

MAX_RAM="50m"
EXTRA_OPTS=(
 --log-driver none
 -p 1883:1883
 -p 8883:8883
 -v $CONTAINER_CONFIG_ROOT/$CONTAINER:/config/mosquitto:ro
 -v $CERT_STORAGE:/config/letsencrypt:ro
 -u $CONTAINER_UID
 -m $MAX_RAM
 )

ENTRYPOINT=(
 /usr/sbin/mosquitto -c /config/mosquitto/mosquitto.conf
 )

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
