#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="mumble"
IMAGE="sudoforge/mumble-server"

MAX_RAM="100m"
EXTRA_OPTS=(
 -p 53368:64738/tcp
 -p 53368:64738/udp
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
