#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh
source $CMD_PATH/lib/certificate.sh

[ $# != 3 ] && show_usage "app external_port proxy_url"
check_cert_env
check_env "CONTAINER_CONFIG_ROOT CERT_ROOT"

APP_NAME=$1
APP_PORT=$2

# get proxy url
if [[ $3 =~ ^[0-9]+$ ]]; then
 PROXY_URL="http://172.17.0.1:$3"
else
 PROXY_URL=${3/local/172.17.0.1}
fi

debug "Starting Nginx on port $APP_PORT with proxy URL: $PROXY_URL"

CONTAINER="nginx-$APP_NAME"
IMAGE="nginxinc/nginx-unprivileged:stable-alpine"

NGINX_CONFIG_ROOT=$CONTAINER_CONFIG_ROOT/nginx
[ ! -d $CONTAINER_CONFIG_ROOT ] && sudo mkdir $CONTAINER_CONFIG_ROOT
NGINX_CONFIG=$NGINX_CONFIG_ROOT/nginx.conf
APP_CONFIG_ROOT=$NGINX_CONFIG_ROOT/conf.d
[ ! -d $APP_CONFIG_ROOT ] && sudo mkdir $APP_CONFIG_ROOT
APP_CONFIG=$APP_CONFIG_ROOT/$APP_NAME.conf
SSL_CONFIG=$CONTAINER_CONFIG_ROOT/ssl

function create_nginx_conf() {
 local conf_file=$1

 local template=$CMD_PATH/lib/nginx_conf.template
 debug "Creating $conf_file ..."
 sudo cp $template $conf_file
}

function create_nginx_app_conf() {
 local conf_file=$1
 local dns_name=$2
 local external_port=$3
 local proxy_url=$4

 local template=$CMD_PATH/lib/nginx_proxy.template
 debug "Creating $conf_file ..."
 sudo cp $template $conf_file

 check_packages "sed" 
 debug "Updating variables in conf file..."
 sudo sed -i "s/{{external_port}}/$external_port/g" $conf_file
 sudo sed -i "s/{{dns_name}}/$DDNS_DOMAIN/g" $conf_file
 sudo sed -i "s%{{proxy_address}}%$proxy_url%g" $conf_file
}

create_nginx_conf $NGINX_CONFIG
create_nginx_app_conf $APP_CONFIG $DDNS_DOMAIN $APP_PORT $PROXY_URL
grant_container_access $NGINX_CONFIG
grant_container_access $SSL_CONFIG

MAX_RAM="100m"
EXTRA_OPTS=(
 -v $NGINX_CONFIG:/etc/nginx/nginx.conf:ro
 -v $APP_CONFIG:/etc/nginx/conf.d/default.conf:ro
 -v $SSL_CONFIG:/etc/nginx/ssl:ro
 -p $APP_PORT:$APP_PORT/tcp
 -u $CONTAINER_UID
 -m $MAX_RAM
 )

ENTRYPOINT=()

#DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
