#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "WEATHER_API_PROVIDER_1 WEATHER_API_KEY_1 WEATHER_PORT GPS_COORDINATES CONTAINER_UID"

CONTAINER="nook"
IMAGE="gadget1999/rpi-nook-weather"

WORK_DIR=/download/container/nook
grant_container_access $WORK_DIR

sudo rm -R $LOG
touch $LOG
grant_container_access $LOG

MAX_RAM="150m"
EXTRA_OPTS=(
 --read-only
 --tmpfs /run
 -e WEATHER_API_PROVIDER_1=$WEATHER_API_PROVIDER_1
 -e WEATHER_API_KEY_1=$WEATHER_API_KEY_1
 -e WEATHER_API_PROVIDER_2=$WEATHER_API_PROVIDER_2
 -e WEATHER_API_KEY_2=$WEATHER_API_KEY_2
 -e WEATHER_API_PROVIDER_3=$WEATHER_API_PROVIDER_3
 -e WEATHER_API_KEY_3=$WEATHER_API_KEY_3
 -e GPS_COORDINATES=$GPS_COORDINATES
 -e QUOTE_FILE=/quotes/quotes.csv
 -v $WORK_DIR/quotes:/quotes:ro
 -v $LOG:/tmp/nook-weather.log
 -p $WEATHER_PORT:8080
 -m $MAX_RAM
 )

ENTRYPOINT=()

case "$1" in
 "debug")
  DEBUG_DOCKER=1
  EXTRA_OPTS+=(-u $CONTAINER_UID)
    ;;

 "debug-dev")
  DEBUG_DOCKER=1
  unset 'EXTRA_OPTS[0]'
  EXTRA_OPTS+=(-e DEBUG=TRUE)
  ENTRYPOINT=(sh -c "echo 'Please enter-container and debug.' ; sleep infinity")
    ;;

 *)
  EXTRA_OPTS+=(-u $CONTAINER_UID)
  ;;
esac

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

if [ "$WEATHER_PORT_EXT" != "" ]; then
 debug "Starting nginx reverse proxy..."
 nginx $CONTAINER $WEATHER_PORT_EXT $WEATHER_PORT 1.2
fi