#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "WEATHER_API_PROVIDER_1 WEATHER_API_KEY_1 WEATHER_PORT_LOCAL CONTAINER_UID"

CONTAINER="nook"
IMAGE="gadget1999/rpi-nook-weather"

sudo rm -R $LOG
touch $LOG
grant_container_access $LOG

MAX_RAM="150m"
EXTRA_OPTS=(
 --read-only
 --tmpfs /run
 -e WEATHER_API_PROVIDER_1=$WEATHER_API_PROVIDER_1
 -e WEATHER_API_KEY_1=$WEATHER_API_KEY_1
 -e WEATHER_API_PROVIDER_2=$WEATHER_API_PROVIDER_2
 -e WEATHER_API_KEY_2=$WEATHER_API_KEY_2
 -e WEATHER_API_PROVIDER_3=$WEATHER_API_PROVIDER_3
 -e WEATHER_API_KEY_3=$WEATHER_API_KEY_3
 -e GPS_COORDINATES=$GPS_COORDINATES
 -v $LOG:/tmp/nook-weather.log
 -p $WEATHER_PORT_LOCAL:8080
 -m $MAX_RAM
 )

ENTRYPOINT=()

case "$1" in
 "debug")
  DEBUG_DOCKER=1
  EXTRA_OPTS+=(-u $CONTAINER_UID)
    ;;

 "debug-dev")
  DEBUG_DOCKER=1
  unset 'EXTRA_OPTS[0]'
  EXTRA_OPTS+=(-e DEBUG=TRUE)
  ENTRYPOINT=(sh -c "echo 'Please enter-container and debug.' ; sleep infinity")
    ;;

 *)
  EXTRA_OPTS+=(-u $CONTAINER_UID)
  ;;
esac

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

if [ "$WEATHER_DOMAIN" != "" ]; then
 debug "Starting nginx reverse proxy with external domain ($WEATHER_DOMAIN)..."
 nginx proxy $WEATHER_DOMAIN $WEATHER_PORT_LOCAL
elif [ "$WEATHER_PORT_EXT" != "" ]; then
 debug "Starting nginx reverse proxy..."
 nginx $CONTAINER $WEATHER_PORT_EXT $WEATHER_PORT_LOCAL 1.2
fi
