#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "DARKSKY_API_KEY DARKSKY_PORT DARKSKY_LOCATION"

CONTAINER="nook"
IMAGE="gadget1999/rpi-nook-weather"

debug "Stop current container"
stop_container $CONTAINER

EXTRA_OPTS=(
 -e DARKSKY_API_KEY=$DARKSKY_API_KEY
 -e GPS_COORDINATES=$DARKSKY_LOCATION
 -v /download/nook/quotes:/quotes
 -p $DARKSKY_PORT:8080
 )

if [ "$1" != "debug" ]; then
 new_container $CONTAINER $IMAGE discard EXTRA_OPTS
else
 new_tmp_container $CONTAINER $IMAGE EXTRA_OPTS entrypoint
fi
