#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "DARKSKY_API_KEY DARKSKY_PORT DARKSKY_LOCATION"

CONTAINER="nook"
IMAGE="gadget1999/rpi-nook-weather"

MAX_RAM="100m"
WORK_DIR=/download/nook
EXTRA_OPTS=(
 -e DARKSKY_API_KEY=$DARKSKY_API_KEY
 -e GPS_COORDINATES=$DARKSKY_LOCATION
 -v $WORK_DIR/quotes:/quotes:ro
 -p $DARKSKY_PORT:8080
 -u $MAIN_USER_ID
 -m $MAX_RAM
 )

ENTRYPOINT=()

if [ "$1" == "debug" ]; then
 DEBUG_DOCKER=1
 ENTRYPOINT=(sleep infinity)
 EXTRA_OPTS=(
  -e DARKSKY_API_KEY=$DARKSKY_API_KEY
  -e GPS_COORDINATES=$DARKSKY_LOCATION
  -v $WORK_DIR/quotes:/quotes:ro
  -p $DARKSKY_PORT:8080
  -v $WORK_DIR/templates:/templates
  -v $WORK_DIR/static:/static
  -v $WORK_DIR/server.py:/server.py
 )
fi

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
