#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "WEATHER_API_PROVIDER WEATHER_API_KEY WEATHER_PORT GPS_COORDINATES CONTAINER_UID"

CONTAINER="nook"
IMAGE="gadget1999/rpi-nook-weather"

WORK_DIR=/download/nook
grant_container_access $WORK_DIR

MAX_RAM="100m"
EXTRA_OPTS=(
 -e WEATHER_API_PROVIDER=$WEATHER_API_PROVIDER
 -e WEATHER_API_KEY=$WEATHER_API_KEY
 -e GPS_COORDINATES=$GPS_COORDINATES
 -v $WORK_DIR/quotes:/quotes:ro
 -p $WEATHER_PORT:8080
 -u $CONTAINER_UID
 -m $MAX_RAM
 )

ENTRYPOINT=()

case "$1" in
 "debug")
  DEBUG_DOCKER=1
  ENTRYPOINT=(sh -c "echo 'Please enter-container and debug.' ; sleep infinity")
  EXTRA_OPTS=(
   -e DARKSKY_API_KEY=$DARKSKY_API_KEY
   -e GPS_COORDINATES=$DARKSKY_LOCATION
   -v $WORK_DIR/quotes:/quotes:ro
   -p $DARKSKY_PORT:8080
   -m $MAX_RAM
   )
    ;;

 "debuglocal")
  DEBUG_DOCKER=1
  ENTRYPOINT=(sh -c "echo 'Please enter-container and debug.' ; sleep infinity")
  EXTRA_OPTS=(
   -e DARKSKY_API_KEY=$DARKSKY_API_KEY
   -e GPS_COORDINATES=$DARKSKY_LOCATION
   -v $WORK_DIR/quotes:/quotes:ro
   -p $DARKSKY_PORT:8080
   -v $WORK_DIR/templates:/templates
   -v $WORK_DIR/static:/static
   -v $WORK_DIR/server.py:/server.py
   )
  ;;

 *)
  ;;
esac

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
