#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="ocr"
IMAGE="ricktorzynski/ocr-tesseract-docker"

MAX_RAM="200m"
EXTRA_OPTS=(
 -p 57257:5000
 -u nobody
 -m $MAX_RAM
 )

ENTRYPOINT=()

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
