#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="openvas"
IMAGE="securecompliance/gvm"

#########################
# Helper functions
#########################

function update_NVD() {
 local DOCKER_CMD="docker exec $CONTAINER"
 
 $DOCKER_CMD greenbone-nvt-sync
 $DOCKER_CMD openvasmd --rebuild --progress
 $DOCKER_CMD greenbone-certdata-sync
 $DOCKER_CMD greenbone-scapdata-sync
 $DOCKER_CMD openvasmd --update --verbose --progress
 $DOCKER_CMD /etc/init.d/openvas-manager restart
 $DOCKER_CMD /etc/init.d/openvas-scanner restart
}

function start_openvas() {
 local internal_port=12443
 [ "$OPENVAS_PORT" != "" ] && $CMD_PATH/nginx openvas $OPENVAS_PORT $internal_port 1.2

 local run_vol=/tmp/$CONTAINER
 [ ! -d $run_vol ] && mkdir $run_vol

 EXTRA_OPTS=(
  -v $CONTAINER:/data
  -e VIRTUAL_HOST=$DDNS_DOMAIN
  -e HTTPS=false
  -p $internal_port:9392
  )

 ENTRYPOINT=()

 new_container_vm $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

 docker logs -f $CONTAINER
}

#########################
# Main entrance
#########################

case $1 in
 update)
  update_NVD
  ;;
 stop)
  stop_container openvas
  ;;
 debug)
  DEBUG_POD=1
  start_openvas
  ;;
 *)
  start_openvas
  ;;
esac
