#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="openvpn"
IMAGE="gadget1999/rpi-openvpn"

MAX_RAM="100m"
EXTRA_OPTS=(
 -p 43268:1194/tcp
 --cap-add=NET_ADMIN
 --tmpfs /run
 -v $CONTAINER:/etc/$CONTAINER
 -m $MAX_RAM
 )

ENTRYPOINT=()

function start_openvpn() {
 new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
}

function add_user() {
 local user=$1
 local profile=/tmp/$user

 log "Generating client profile: $user"
 $DOCKER_CMD run -v $CONTAINER:/etc/openvpn --rm -it $IMAGE \
   easyrsa build-client-full $user

 log "Exporting client profile to: $profile"
 $DOCKER_CMD run -v $CONTAINER:/etc/openvpn --rm $IMAGE \
   ovpn_getclient $user > $profile

 share $profile
}

function setup_openvpn() {
 log "Creating OpenVPN volume: $CONTAINER"
 $DOCKER_CMD volume create --name $CONTAINER

 check_env "DDNS_DOMAIN"
 log "Generating config environment for [$DDNS_DOMAIN] ..."
 $DOCKER_CMD run -v $CONTAINER:/etc/openvpn --rm -it $IMAGE \
   ovpn_genconfig -u $DDNS_DOMAIN

 log "Generating PKI ..."
 $DOCKER_CMD run -v $CONTAINER:/etc/openvpn --rm -it $IMAGE \
   ovpn_initpki
}

#########################
# Main entrance
#########################

case $1 in
 setup)
  setup_openvpn
  ;;
 adduser)
  add_user $2
  ;;
 debug)
  DEBUG_DOCKER=1
  start_openvpn
  ;;
 *)
  start_openvpn
  ;;
esac
