#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="openvas"
IMAGE="mikesplain/openvas"

EXTRA_OPTS=(
 -v $CONTAINER:/var/lib/openvas/mgr/
 -p 443:443
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

docker logs -f openvas
