#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="openvpn"
IMAGE="kylemanna/openvpn"

MAX_RAM="100m"
EXTRA_OPTS=(
 -p 43268:1194/tcp
 --cap-add=NET_ADMIN
 -v $CONTAINER:/etc/$CONTAINER
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
