#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="tinyproxy"
IMAGE="vimagick/tinyproxy"

echo "Stop current container"
stop_container $CONTAINER

EXTRA_OPTS=(
 -p 56291:8888
 -v $CONTAINER:/etc/$CONTAINER
 )
new_container $CONTAINER $IMAGE discard EXTRA_OPTS
