#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="tinyproxy"
IMAGE="vimagick/tinyproxy"

MAX_RAM="50m"
EXTRA_OPTS=(
 -p 56291:8888
 -v $CONTAINER:/etc/$CONTAINER
 -u nobody
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
