#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

check_env "SAMBA_LOCAL_PATH SAMBA_SHARE SAMBA_USER SAMBA_PASSWORD"

CONTAINER="samba"
IMAGE="gadget1999/rpi-samba"

EXTRA_OPTS=(
 -p 139:139
 -p 445:445
 -p 137:137/udp
 -p 138:138/udp
 -v "$SAMBA_LOCAL_PATH:/$SAMBA_SHARE"
 -e USER="$SAMBA_USER:$SAMBA_PASSWORD"
 -e SHARE="$SAMBA_SHARE:/$SAMBA_SHARE:rw:$SAMBA_USER"
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
