#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

# SAMBA_SHARE format: Share:/data:rw:$SAMBA_USER
check_env "SAMBA_LOCAL_PATH SAMBA_SHARE SAMBA_USER SAMBA_PASSWORD CONTAINER_UID CONTAINER_PLATFORM"

$CMD_PATH/mount-usb-drive

CONTAINER="samba"
IMAGE="gadget1999/rpi-samba:$CONTAINER_PLATFORM"

grant_container_access $SAMBA_LOCAL_PATH

MAX_RAM="100m"
EXTRA_OPTS=(
 --log-driver none
 -p 139:10139
 -p 445:10445
 -p 137:10137/udp
 -p 138:10138/udp
 --tmpfs /run
 --tmpfs /var/cache/samba
 --mount type=tmpfs,destination=/var/lib/samba/private/msg.sock,tmpfs-mode=700 
 --tmpfs /ram
 -v $SAMBA_LOCAL_PATH:/data
 -e SMB_VER="SMB3_11"
 -e PUID=$CONTAINER_UID
 -e PGID=$CONTAINER_UID
 -e USER="$SAMBA_USER:$SAMBA_PASSWORD"
 -e SHARE="$SAMBA_SHARE"
 -e SHARE2="$SAMBA_SHARE2"
 -e SHARE3="$SAMBA_SHARE3"
 -e SHARE4="$SAMBA_SHARE4"
 -m $MAX_RAM
 )

ENTRYPOINT=()

if [ "$1" == "debug" ]; then
 DEBUG_DOCKER=1
 ENTRYPOINT=(sh)
fi

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
