#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

IMAGE="jumanjiman/ssllabs-scan"

EXTRA_OPTS=(
 --read-only
 --cap-drop all
 )

ENTRYPOINT=(
 "$@"
 )

container_cli $IMAGE EXTRA_OPTS ENTRYPOINT
