#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh
source $CMD_PATH/lib/certificate.sh

check_env "SSR_PASSWORD DDNS_DOMAIN"

CONTAINER="ssr-only"
IMAGE="shadowsocks/shadowsocks-libev"

PORT=8443

debug "Stop current container"
stop_container $CONTAINER

EXTRA_OPTS=(
 -e PASSWORD=$SSR_PASSWORD
 -p $PORT:8388
 -p $PORT:8388/udp
 )

if [ "$1" != "debug" ]; then
 new_stateless_container $CONTAINER $IMAGE EXTRA_OPTS
else
 new_tmp_container $CONTAINER $IMAGE EXTRA_OPTS entrypoint
fi
