#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh
source $CMD_PATH/lib/certificate.sh

check_env "SSR_PASSWORD DDNS_DOMAIN"

CONTAINER="ssr-only"
IMAGE="shadowsocks/shadowsocks-libev"

PORT=8443

# use isolated network
create_docker_network bridge sandbox

MAX_RAM="100m"
EXTRA_OPTS=(
 -e PASSWORD=$SSR_PASSWORD
 --tmpfs /run
 --network sandbox
 -p $PORT:8388
 -p $PORT:8388/udp
 -u nobody
 -m $MAX_RAM
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT
