#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="youtube"
IMAGE="alexta69/metube"

check_env "YOUTUBE_ROOT YOUTUBE_PORT_LOCAL"

[ ! -d $YOUTUBE_ROOT ] && sudo mkdir -p $YOUTUBE_ROOT
[ ! -d $YOUTUBE_ROOT ] && fatal_error "Failed to create folder: $YOUTUBE_ROOT"
grant_container_access $YOUTUBE_ROOT

# use isolated network
create_docker_network bridge sandbox

EXTRA_OPTS=(
 --network sandbox
 -p $YOUTUBE_PORT_LOCAL:8081
 -v $YOUTUBE_ROOT:/downloads
 -e DELETE_FILE_ON_TRASHCAN=true
 -e OUTPUT_TEMPLATE="%(title).80s.%(ext)s"
 -e YTDL_OPTIONS='{"cookiefile":"/downloads/.metube/cookies.txt"}' 
 -u $CONTAINER_UID
 )

ENTRYPOINT=()

[ "$1" == "debug" ] && DEBUG_DOCKER=1
new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

if [ "$YOUTUBE_PORT_EXT" != "" ]; then
 debug "Starting nginx reverse proxy..."
 nginx $CONTAINER $YOUTUBE_PORT_EXT $YOUTUBE_PORT_LOCAL 1.2
fi
