#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER="youtube-ui"
IMAGE="ghcr.io/alexta69/metube"

check_env "YOUTUBE_ROOT"

YOUTUBE_PORT=15936
YOUTUBE_PORT_EXT=22287

[ ! -d $YOUTUBE_ROOT ] && sudo mkdir -p $YOUTUBE_ROOT
[ ! -d $YOUTUBE_ROOT ] && fatal_error "Failed to create folder: $YOUTUBE_ROOT"
grant_container_access $YOUTUBE_ROOT

# use isolated network
create_docker_network bridge sandbox

EXTRA_OPTS=(
 --network sandbox
 -p $YOUTUBE_PORT:8081
 -v $YOUTUBE_ROOT:/downloads
 -e DELETE_FILE_ON_TRASHCAN=true
 -u $CONTAINER_UID
 )

ENTRYPOINT=()

new_container_service $CONTAINER $IMAGE EXTRA_OPTS ENTRYPOINT

debug "Starting nginx reverse proxy..."
nginx $CONTAINER $YOUTUBE_PORT_EXT $YOUTUBE_PORT
