version: '2.0'
services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_KEY}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${SEAFILE_DATA}/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:latest
    restart: unless-stopped
    container_name: seafile-memcached
    entrypoint: memcached -m 128
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    restart: unless-stopped
    container_name: seafile
    ports:
      - "${SEAFILE_PORT}:443"
    volumes:
      - ${SEAFILE_DATA}/data:/shared
    env_file:
      - ${SEAFILE_DATA}/.env          
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_DB_KEY}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=true
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_FQDN}
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
