#!/usr/bin/env bash

cd /tmp
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
sudo sh onboard_agent.sh --purge
sudo /etc/opt/microsoft/omsagent
sudo /var/opt/microsoft/omsagent
