#!/usr/bin/env bash

cd /tmp
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
$SUDO sh onboard_agent.sh --purge
$SUDO /etc/opt/microsoft/omsagent
$SUDO /var/opt/microsoft/omsagent
