version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_KEY}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - /opt/seafile/data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_DB_KEY}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=false
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
