#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
#ENABLE_LOGGING=0
#DEBUG=0

if [ ! -e ~/.ssh ]; then
 debug "Creating .ssh folder"
 mkdir ~/.ssh
 touch ~/.ssh/authorized_keys
fi

chmod 700 ~
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

nano ~/.ssh/authorized_keys
