#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "/usr/bin/pwsh"

# usage: az cmdlet args

CMDLET="$1"

PWSH_DIR=$CMD_PATH/azure
PWSH_CMD=$PWSH_DIR/$CMDLET.ps1

sudo pwsh $PWSH_CMD $2 $3 $4

# seems PowerShell will leave some trash behind
sudo rm /tmp/*.pwsh
