#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh
source $CMD_PATH/lib/disk.sh
#ENABLE_LOGGING=0
#DEBUG=0

check_disk_env

$CMD_PATH/mount-usb-drive

# Backup Raspberry Pi SD Card via dual-boot
BACKUP_FOLDER="/media/USBHDD/Share/Backup/System/RPi/rpi4-image-$TODAY"
sudo mkdir -p $BACKUP_FOLDER
sudo chmod 777 $BACKUP_FOLDER
assert_success "Creating backup folder [$BACKUP_FOLDER]"

# Raspberry Pi disk and partitions
# the partition layout is /boot, /root (main), /root (backup)
# when need to backup, boot into backup root, then run this command
DISK=mmcblk0
backup_disk $DISK $BACKUP_FOLDER
grant_container_access $BACKUP_FOLDER/*
