#!/usr/bin/env bash

export LANG="C.UTF-8"

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_env "BAIDU_DOWNLOAD BAIDU_UPLOAD"

CMD="/usr/local/bin/bypy"
check_packages "$CMD"

lock

function download_BaiduPan() {
 local remote_root=$1
 local local_root=$2

 # in case file name has space, it could cause list to split
 # using IFS to fix it
 IFS=$'\n'
 # use sed to strip out header line
 local items=($(bypy ls $remote_root '$f'))
 unset IFS
 for item in "${items[@]}"; do
  [[ "$item" == *":"* ]] && continue
  local path="$remote_root/$item"
  log "Dowloading $path"

  $CMD -d --chunk 1MB --move \
   download "$path" "$local_root/$item"
 done
}

function upload_BaiduPan() {
 local local_root=$1
 local remote_root=$2

 # in case file name has space, it could cause list to split
 # using IFS to fix it
 IFS=$'\n'
 local items=($(ls -1 $local_root))
 unset IFS
 for item in "${items[@]}"; do
  local path="$local_root/$item"
  log "Uploading $path"

  $CMD -d --chunk 1MB --move \
   upload "$path" "$remote_root/$item"
 done
}

download_BaiduPan "Downloads" "$BAIDU_DOWNLOAD"

upload_BaiduPan $BAIDU_UPLOAD Uploads
