#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_env "SHARE_SERVER SHARE_NAME SHARE_USER SHARE_PWD"

SMB_VER="vers=3.11"

MOUNT_ROOT=/tmp/CIFS
SHARE_MOUNTPOINT=$MOUNT_ROOT/$SHARE_NAME
SHARE_UNC=//$SHARE_SERVER/$SHARE_NAME

function mount_cifs_share() {
 local unc_path=$1
 local user=$2
 local password=$3
 local mount_point=$4

 if [ "$(df | grep ""$unc_path"")" ]; then
  debug "Share already mounted."
  return
 fi

 if [ ! -d $MOUNT_ROOT ] ; then
  debug "Creating mount point root: $MOUNT_ROOT"
  sudo mkdir $MOUNT_ROOT
 fi

 if [ ! -d $mount_point ] ; then
  debug "Creating mount point: $mount_point"
  sudo mkdir $mount_point
 fi

 if [ "x$SMB_VER" == "x" ]; then
  log "Mounting [$unc_path] to [$mount_point] (SMB 1.0)..."
 else
  log "Mounting [$unc_path] to [$mount_point] (SMB $SMB_VER)..."
 fi

 sudo /bin/mount -t cifs \
  -o username=$user,password=$password,rw,iocharset=utf8,file_mode=0777,dir_mode=0777,$SMB_VER \
  $unc_path $mount_point
 log "Completed."
}

case $1 in
 unmount)
  sudo umount $SHARE_MOUNTPOINT
  ;;
 *)
  mount_cifs_share $SHARE_UNC $SHARE_USER $SHARE_PWD $SHARE_MOUNTPOINT
  ;;
esac
