#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_root

function zerofile() {
 local file=$1
 [ ! -e "$file" ] && return

 echo "Truncate $file"
 sudo truncate -s 0 $file
}

for i in /tmp/*.log /tmp/*.txt;
do
 zerofile $i
done
