#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_root

function zerofile() {
 local file=$1
 [ ! -e "$file" ] && return # file does not exist
 [ ! -s "$file" ] && return # file empty

 debug "Truncate $file"
 $SUDO truncate -s 0 $file
 if [ $? -ne 0 ]; then
  log_error "Truncating $file failed. Retry..."
  truncate -s 0 $file
  if [ $? -ne 0 ]; then
   log_error "Deleting $file..."
   $SUDO rm $file
  fi
 fi
}

for i in /tmp/*.log /tmp/*.txt;
do
 zerofile $i
done
