#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "pgrep"

# Clean up orphan lock files
# The reason to use lock files instead of check process name is that 
# lock files are faster, easier to avoid race conditions

function clean_lock() {
 local lockfile=$1
 local filename="$(basename -- "$lockfile")"
 local app="${filename%.*}"
 
 debug "Checking lock file $lockfile (App: $app) ..."
 [ ! -e $lockfile ] && return
 
 # check if the lock file is orphaned
 debug "Found lock file, check if $app is still running..."
 local running=`pgrep -f $app &> /dev/null && echo yes || echo no`
 if [ "$running" == "no" ]; then
  log_error "Lock file is orphaned and will be deleted."
  $SUDO rm $lockfile
 else
  debug "App is running, so it's normal."
 fi
}

for filename in /tmp/*.lock; do
 clean_lock $filename
done
