#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

# Use dropbox to automatically collect important app logs
check_packages "$CMD_PATH/dropbox"

HOST=$(hostname)

YEAR=$(date +%Y)
if [ "$YEAR" -lt "2012" ]; then
 log_error "System time (Year: $YEAR) is invalid."
 exit 1
fi

function upload_log() {
 local app=$1
 local logfile=$2

 debug "Checking $logfile ..."
 if [ ! -e $logfile ]; then
  debug "$logfile does not exist."
  return
 fi
 
 if [ ! -s $logfile ]; then
  debug "$logfile is empty."
  return
 fi
 
 local remotefile="Logs/$HOST/-$app-/$TODAY-$app.txt"
 log "Uploading [$logfile] to dropbox [$remotefile] ..."
 $CMD_PATH/dropbox upload $logfile $remotefile >> $LOG
}

for APP in ${APP_LOGS[*]}; do
 APPLOG="/tmp/$APP.log"
 debug "Checking $APPLOG ..."
 upload_log $APP $APPLOG
done
