#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
#ENABLE_LOGGING=0
#DEBUG=0

DISK=$(df --output=source / | awk -F'[/0-9]' 'NR==2 {print $3}')
WRITTEN_MB=$(cat /sys/block/$DISK/stat | awk '{print $7*512/1024/1024}')
log "/dev/$DISK written $WRITTEN_MB MB"
