#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/disk.sh
#ENABLE_LOGGING=0
#DEBUG=0

case $1 in
 backup-disk)
  backup_disk $2
  ;;
 backup-disk-info)
  backup_partition_table $2
  ;;
 backup-partition)
  backup_partition $2
  ;;
 restore)
  restore_disk $2
  ;;
 *)
  show_usage "backup-disk|backup-disk-info|backup-partition|restore dev_name"
  ;;
esac
