#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

TEMPLATE=$CMD_PATH/cmd-template
CMD_FILE=$CMD_PATH/$1

if [ ! -e $CMD_FILE ]; then
    debug "Command [$1] does not exist"
    exit 1
fi

$SUDO nano $CMD_FILE

