#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

function edit_user_cron() {
 local cronfile=~/mycron
 crontab -l > $cronfile
 nano -c $cronfile
 crontab $cronfile
 crontab -l
}

function edit_sys_cron() {
 local cronfile="/etc/cron.d/tasks"

 nano -c $cronfile
 cat $cronfile > /root/syscron
 cat $cronfile
}

if [ "$(whoami)" == "root" ]; then
 edit_sys_cron
else
 edit_user_cron
fi
