#!/bin/bash

# Define an array of directories to exclude
excluded_dirs=(
  "/proc" "/sys" "/run" "/dev"
  "/media" "/mnt"
  "/tmp" "/var/log"
  )

find_opts=()
for dir in "${excluded_dirs[@]}"; do
  find_opts+=(-path "$dir" -o)
done

INTERVAL=$1
echo "Searching whole disk for changes over last $INTERVAL minutes"
sudo find / \( "${find_opts[@]}" -false \) -prune -o \
  -mmin -$INTERVAL -printf "%TY-%Tm-%Td %TH:%TM %s %p\n"
