#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/email.sh
source $CMD_PATH/lib/firebase.sh
#ENABLE_LOGGING=0
#DEBUG=0

check_env "METRICS_FB_URL METRICS_FB_KEY"
check_env "MAIN_EMAIL EMAIL_SENDER EMAIL_API_KEY"
check_packages "curl jq"

if [ $# == 0 ]; then
 check_env "HOST_WATCHLIST"
else
 HOST_WATCHLIST="$*"
fi
check_packages "jq"

MAX_DELAY=7300

function check_alive() {
 local host=$1
 local timestamp=$(firebase_get_attr "heartbeat/$host" "timestamp")
 if [ "$timestamp" == "null" ] || [ "$timestamp" == "" ] ; then
  send_host_report $host "Failed to get heartbeat for host [$host]."
  return
 fi

 local delta=$(( $(date +%s) - $timestamp ))
 if (( $delta > $MAX_DELAY )); then
  send_host_report $host "[$host]: $delta seconds passed since last update. Host may be down."
  return
 fi

 local temperature=$(firebase_get_attr "heartbeat/$host" "temperature")
 debug "[$host] ($temperature°): last seen $delta seconds ago." 
}

function send_host_report() {
 local host=$1
 local error=$2
 log_error "Sending error report: $error"
 check_email_env
 send-email \
  "Server [$host] may be down" \
  "$error"
}

firebase_setup $METRICS_FB_URL $METRICS_FB_KEY

for host in ${HOST_WATCHLIST[*]}; do
  check_alive $host
done
