#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/firebase.sh
#ENABLE_LOGGING=0
#DEBUG=0

check_env "METRICS_FB_URL METRICS_FB_KEY"
check_packages "curl jq"

function get_cpu_temperature() {
 local temperature=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null \
          | awk '{print $1/1000}' | sort -nr | head -1)
 echo $temperature
}

function fb_send_metrics() {
 local host=$(hostname)
 local temperature=$(get_cpu_temperature)
 local msg=$( \
   jq -n '{timestamp:$epoch, updated:$time, temperature:$temperature}' \
    --arg epoch $EPOCH \
    --arg time $NOW \
    --arg temperature "$temperature" \
   }
  )

 #debug "Send metrics: $msg"
 firebase_send "heartbeat/$host" "$msg"
}

firebase_setup $METRICS_FB_URL $METRICS_FB_KEY

fb_send_metrics
