#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/email.sh
source $CMD_PATH/lib/certificate.sh

check_cert_env
[ "$1" == "force" ] && FORCE="--force"

if [ "$ENABLE_JIT_ACCESS" != "" ]; then
 log "Enable firewall JIT access"
 $CMD_PATH/$ENABLE_JIT_ACCESS
fi

log "Begin to issue certificate: $DDNS_DOMAIN"
if ! issue_certificate_docker $FORCE; then
 log_error "Certificate was not issued."
 exit
fi

if [ "$MAIN_EMAIL" != "" ]; then
 log "Sending email notification to $MAIN_EMAIL"
 check_email_env
 send_email \
  $MAIN_EMAIL \
  "$DDNS_DOMAIN certificate issued" \
  "Enjoy!"
fi

log "Copying new certificates to $CERT_STORAGE"
$SUDO mkdir -p $CERT_STORAGE
$SUDO cp $CERT_FULLCHAIN $CERT_STORAGE/fullchain.pem
$SUDO cp $CERT_KEY $CERT_STORAGE/privkey.pem
ls -l $CERT_STORAGE
