#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

function list_packages_centos() {
 rpm -qa --qf '%{INSTALLTIME:date}: %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' | sort -n
}

function list_packages_debian() {
 grep " installed " /var/log/dpkg.log
}

case $OS in
 debian)
  log "List installed packages (Debian)"
  list_packages_debian
  ;;
 centos)
  log "List installed packages (CentOS)"
  list_packages_centos
  ;;
 *)
  log_error "Unknown system type"
  exit 1
  ;;
esac
