#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "python3 ffmpeg"
check_env "M3U8_WORK_DIR FFMPEG"

export M3U8_WORK_DIR
export FFMPEG

# Python VENV sometimes cannot validate certificates, use OS certs
OS_CERTS="/etc/ssl/certs/ca-certificates.crt"
export SSL_CERT_FILE=$OS_CERTS
export REQUESTS_CA_BUNDLE=$OS_CERTS

[ "$1" == "test" ] && \
 "$PYTHON_VENV"python3 $CMD_PATH/python/m3u8-downloader.py \
  "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" "Test $NOW" "-" && \
 exit 0

"$PYTHON_VENV"python3 $CMD_PATH/python/m3u8-downloader.py "$@"
