#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/disk.sh
#ENABLE_LOGGING=0
#DEBUG=0

MOUNT_POINT=/tmp/vhd

function usage() {
 show_usage "on vhd_file_path partition_number | off"
}

case $1 in
 on)
  [ "$#" != "3" ] && usage && exit 1
  VHD_FILE="$2"
  PARTITION_NUM=$3
  mount_bitlocker_vhd $VHD_FILE $PARTITION_NUM $MOUNT_POINT
  ;;
 off)
  unmount_bitlocker_vhd $MOUNT_POINT
  ;;
 *)
  usage
  ;;
esac
