#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
#ENABLE_LOGGING=0
#DEBUG=0

PARTITION=/dev/sdb2

case $1 in
 on)
  mount_bitlocker $PARTITION
  ;;
 off)
  unmount_bitlocker $PARTITION
  ;;
 *)
  mount_bitlocker $PARTITION
  ;;
esac
