#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/disk.sh
#ENABLE_LOGGING=0
#DEBUG=0

MOUNT_POINT=/tmp/vhd

function usage() {
 show_usage "vhd_file_path [RW] | off"
}

case $1 in
 off)
  unmount_bitlocker_vhd $MOUNT_POINT
  ;;
 *)
  VHD_FILE="$1"
  MOUNT_MODE="$2"
  unmount_bitlocker_vhd $MOUNT_POINT
  # seems partition number is always 2
  mount_bitlocker_vhd $VHD_FILE 2 $MOUNT_POINT $MOUNT_MODE
  ;;
esac
