#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/mqtt.sh
source $CMD_PATH/lib/firebase.sh

check_mqtt_env
check_firebase_env

# only one instance can run
lock

#######################
# Event Handlers
#######################

function example_switch_action() {
 local state=$1
 case $state in
  on)
   turn-on-switch &
   firebase_send switch $1
   ;;
  off)
   turn-off-switch &
   firebase_send switch $1
   ;;
 esac
}

function mqtt_callback() {
 local cmd=$1
 local arg=$2

 log "Received command: $cmd ($arg)"
 case $cmd in
  example_switch)
   example_switch_action $arg
   ;;
 esac
}

start_mqtt_agent
