#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

[ "$1" == "" ] && show_usage "command-name"

TEMPLATE=$CMD_PATH/lib/cmd-template
CMD_FILE=$CMD_PATH/$1

if [ ! -e $CMD_FILE ]; then
 $SUDO cp $TEMPLATE $CMD_FILE
 $SUDO chmod +x $CMD_FILE
 $SUDO nano $CMD_FILE
else
    debug "Command [$1] already exists."
fi
