#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

source common.sh

TEMPLATE=$CMD_PATH/cmd-template
CMD_FILE=$CMD_PATH/$1

if [ ! -e $CMD_FILE ]; then
 $SUDO cp $TEMPLATE $CMD_FILE
 $SUDO chmod +x $CMD_FILE
 $SUDO nano $CMD_FILE
else
    debug "Command [$1] already exists."
fi
