#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/docker.sh

CONTAINER_NAME="openvas"
IMAGE_NAME="mikesplain/openvas"
EXTRA_OPTS=(
 -v $CONTAINER_NAME:/var/lib/openvas/mgr/
 -p 443:443
 )

new_container $CONTAINER_NAME $IMAGE_NAME discard EXTRA_OPTS

docker logs -f openvas