#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

source common.sh

TASKS=( \
 ddns \
 ssr \
)

for TASK in ${TASKS[*]}; do
  log "Starting $TASK..."
  ($TASK)&
  sleep 5
done
