#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh

TASKS=( \
 ddns \
 ssr \
)

for TASK in ${TASKS[*]}; do
  log "Starting $TASK..."
  ($CMD_PATH/$TASK)&
  sleep 5
done
