#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh
source $CMD_PATH/email.sh
source $CMD_PATH/certificate.sh

check_cert_env

if [ "$ENABLE_JIT_ACCESS" != "" ]; then
 log "Enable firewall JIT access"
 $CMD_PATH/$ENABLE_JIT_ACCESS
fi

if [ "$1" == "force" ]; then
 FORCE_RENEW="--force"
fi

log "Begin to renew certificate: $DDNS_DOMAIN"
if renew_certificate $FORCE_RENEW; then
 exit
else
 log "Succeeded."
fi

if [ "$MAIN_EMAIL" != "" ]; then
 log "Sending email notification to $MAIN_EMAIL"
 check_email_env
 send_email \
  $MAIN_EMAIL \
  "$CERT_DOMAIN certificate renewed" \
  "Enjoy!"
fi

if [ "$CERT_STORAGE" != "" ]; then
 log "Copying new certificates to $CERT_STORAGE"
 $SUDO cp $CERT_FULLCHAIN $CERT_STORAGE/fullchain.pem
 $SUDO cp $CERT_KEY $CERT_STORAGE/privkey.pem
 ls -l $CERT_STORAGE
fi
