#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh
source $CMD_PATH/email.sh

check_env "DDNS_DOMAIN CERT_CMD CERT_ROOT CERT_METHOD CERT_LOCAL_PORT"

FORCE_RENEW=$1
if [ "$FORCE_RENEW" == "force" ]; then
 FORCE_RENEW="--force"
else
 FORCE_RENEW=""
fi

RENEW_CMD_HTTP="$SUDO $CERT_CMD --renew $FORCE_RENEW -d $DDNS_DOMAIN --standalone --httpport $CERT_LOCAL_PORT"
RENEW_CMD_TLS="$SUDO $CERT_CMD --renew $FORCE_RENEW --ecc -d $DDNS_DOMAIN --standalone --alpn --tlsport $CERT_LOCAL_PORT"
ECC=""

case $CERT_METHOD in
 http)
  RENEW_CMD=$RENEW_CMD_HTTP
  ECC=""
  ;;
 tls)
  RENEW_CMD=$RENEW_CMD_TLS
  ECC="_ecc"
  ;;
 *)
  log_error "Unknown certificate renew type: $CERT_METHOD"
  exit 1
  ;;
esac

if [ "$ENABLE_JIT_ACCESS" != "" ]; then
 log "Enable firewall JIT access"
 $ENABLE_JIT_ACCESS
fi

log "Begin to renew certificate"
OUTPUT="$($RENEW_CMD)"
log "Result: $OUTPUT"

if [[ $OUTPUT != *"Your cert key"* ]]; then
 exit
fi

if [ "$MAIN_EMAIL" != "" ]; then
 log "Sending email notification to $MAIN_EMAIL"
 check_email_env
 send_email \
  $MAIN_EMAIL \
  "$CERT_DOMAIN certificate renewed" \
  "Enjoy!"
fi

if [ "$CERT_STORAGE" != "" ]; then
 log "Copying new certificates to $CERT_STORAGE"
 CERT_PATH="$CERT_ROOT/$DDNS_DOMAIN"$ECC
 $SUDO cp $CERT_PATH/fullchain.cer $CERT_STORAGE/fullchain.pem
 $SUDO cp $CERT_PATH/$DDNS_DOMAIN.key $CERT_STORAGE/privkey.pem
 ls -l $CERT_STORAGE
fi
