#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_env "INFLUXDB_API_ENDPOINT INFLUXDB_API_TOKEN
           INFLUXDB_TENANT INFLUXDB_BUCKET"

lock

export INFLUXDB_API_ENDPOINT
export INFLUXDB_API_TOKEN
export INFLUXDB_TENANT
export INFLUXDB_BUCKET
[ "$FAN_CONTROL_PIN" != "" ] && export FAN_CONTROL_PIN
[ "$FAN_ON_TEMP" != "" ] && export FAN_ON_TEMP
[ "$FAN_OFF_TEMP" != "" ] && export FAN_OFF_TEMP

[ "$1" == "debug" ] && export DEBUG
# no need to use sudo if user in gpio group
# (if use sudo, use 'sudo -E' to keep exported variables)
python3 $CMD_PATH/python/rpi-fan.py
