#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

TASKS=$1
for TASK in ${TASKS[*]}; do
 if [[ "$TASK" == *"&" ]]; then
  log "Starting $TASK (background) ..."
  ($CMD_PATH/$TASK)&
  sleep 20
 else
  log "Starting $TASK ..."
  $CMD_PATH/$TASK
 fi
done