#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_env "SENDGRID_API_KEY MAIN_EMAIL MONITOR_HOSTS"

SSLSCAN_CLI=$CMD_PATH/sslscan
SSLSCAN_OUTPUT=/tmp/sslscan.json

function scan_one_server() {
 local server=$1

 debug "Scanning $server..."
 $SSLSCAN_CLI $server
 if [ ! -e $SSLSCAN_OUTPUT ]; then
  log_error "Failed to scan $server"
  return
 fi

 # parse the output
 local issues=$(cat $SSLSCAN_OUTPUT | jq '.[] | "\(.id) (\(.severity)): \(.ip)"')
 log "Issues found for $server: \n$issues"
}

function scan_server_list() {
 local server_list=$1

 while IFS= read -r line; do
  scan_one_server $line
 done < "$server_list"
}

scan_server_list $MONITOR_HOSTS
