#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/email.sh

check_env "EMAIL_API_KEY"
check_email_env

[ $# != 2 ] && show_usage "subject body"

SUBJECT=$1
BODY=$2

if [ "$EMAIL_API_KEY" == "$SENDGRID_API_KEY" ]; then
 log "Sending email to $MAIN_EMAIL (SendGrid)"
 send_email_sendgrid $MAIN_EMAIL "$SUBJECT" "$BODY"
elif [ "$EMAIL_API_KEY" == "$BREVO_API_KEY" ]; then
  log "Sending email to $MAIN_EMAIL (Brevo)"
  send_email_brevo $MAIN_EMAIL "$SUBJECT" "$BODY"
else
  fatal_error "Unsupported email provider."
fi
