#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

# base
PACKAGES="curl deborphan htop mc nano ncdu p7zip screen sudo wget unzip"

# mqtt, firebase, acme.sh, ddns
PACKAGES="$PACKAGES dnsutils jq mosquitto-clients socat"

# pyload, pyby, pybox
PACKAGES="$PACKAGES python python-requests python-poster python-mechanize python-openssl"

function setup_packages_centos() {
 sudo yum install -y $PACKAGES
}

function setup_packages_debian() {
 sudo apt-get install -y $PACKAGES
}

check_os_type

case $OS_TYPE in
 debian)
  log "Installing $PACKAGES (Debian)"
  setup_packages_debian
  ;;
 centos)
  log "Installing $PACKAGES (CentOS)"
  setup_packages_centos
  ;;
 *)
  log_error "Unknown system type"
  exit 1
  ;;
esac
