#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "dropbox"

FILE_PATTERN="$@"

function dropbox_upload() {
 local object=$1
 local target=$2

 if [ ! -f $object ]; then
  debug "Finding full path of $object ..."
  object=$(which $object)
  if [ "$object" == "" ]; then
   debug "Cannot find the file: $1"
   return
  fi
 fi

 local filename=$(basename $object)
 local remote_path="/$target/$filename"
 debug "Uploading $object to $remote_path ..."
 dropbox upload $object $remote_path
}

function copy2share() {
 local object=$1
 if [ ! -f $object ]; then
  object=$(which $object)
  if [ "$object" == "" ]; then
   debug "Cannot find the file: $1"
   return
  fi
 fi

 local filename=$(basename $object)
 local remote_path="/mnt/share/$filename"
 debug "Copying $object to $remote_path ..."
 cp $object $remote_path
}

for file in $FILE_PATTERN; do
# dropbox_upload $file share/$TODAY
 copy2share $file
done
