#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh
source $CMD_PATH/docker.sh

CONTAINER="ssr"
IMAGE="shadowsocks/shadowsocks-libev"
PORT=443

log "Stop current container"
stop_container $CONTAINER

log "Pull latest $IMAGE"
docker pull $IMAGE

log "Starting container: $CONTAINER"

docker run -d --rm \
 --name $CONTAINER \
 -v /etc/hosts:/etc/hosts \
 -e PASSWORD=$SSR_PASSWORD \
 -p $PORT:8388 \
 -p $PORT:8388/udp \
 $IMAGE

sleep 3
docker ps
