#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh
source $CMD_PATH/docker.sh

CONTAINER="ssr"
IMAGE="acrisliu/shadowsocks-libev"
PORT=443
PASSWORD=$($CMD_PATH/ssr-password)

V2RAY_DOMAIN=$($CMD_PATH/fqdn)
V2RAY_ARGS="ARGS=--plugin v2ray-plugin --plugin-opts server;mode=quic;host=$V2RAY_DOMAIN"

log "Stop current container"
stop_container $CONTAINER

log "Pull latest $IMAGE"
docker pull $IMAGE

log "Starting container: $CONTAINER"

docker run -d --rm \
 --name $CONTAINER \
 -e "$V2RAY_ARGS" \
 -v /root/.acme.sh:/root/.acme.sh \
 -v /etc/hosts:/etc/hosts \
 -v /root/.acme.sh:/root/.acme.sh \
 -v /etc/hosts:/etc/hosts \
 -e PASSWORD=$PASSWORD \
 -p $PORT:8388 \
 -p $PORT:8388/udp \
 $IMAGE

sleep 3
docker ps
