#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

source common.sh

sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get -y autoremove
sudo reboot
