#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/common.sh

NEED_CONFIRM="yes"
function copy_file() {
 local source=$1
 local target=$2

 # copy if target does not exist
 if [ ! -f $target ]; then
  log "Copying $target"
  $SUDO cp $source $target
  return 0
 fi

 # do not overwrite conf files
 if [[ $target == *".conf" ]]; then
  return 0
 fi

 # ask for confirmation if files are different
 local md5source=( $(md5sum "$source") )
 local md5target=( $(md5sum "$target") )
 if [ $md5source == $md5target ]; then
#  debug "Skipping unchanged file: $target"
  return 0
 fi

 # file changed, asking for confirmation
 if [ $NEED_CONFIRM != "yes" ]; then
  log "Updating $target"
  $SUDO cp $source $target
  return 0
 fi

 diff $source $target
 read -p "Overwrite $target (Yes/[No]/All)?" choice
 case "$choice" in
  y|Y )
   log "Updating $target"
   $SUDO cp $source $target
   ;;
  A|a )
   NEED_CONFIRM="no"
   log "Updating $target"
   $SUDO cp $source $target
   ;;
  * )
   return 1
   ;;
 esac
}

function copy_files() {
 local files=$1
 local folder=$2

 for filepath in $files; do
  filename=$(basename "$filepath")
  target=$folder/$filename
  copy_file $filepath $target
 done
}

GITHUB_URL="https://github.com/gadget1999/linux/archive/master.zip"
TMP_ZIP=/tmp/master.zip
TMP_FOLDER=/tmp/linux-master
TMP_CMD_FOLDER=/tmp/linux-master/scripts

cd /tmp

wget -q $GITHUB_URL
unzip -qq -o $TMP_ZIP

copy_files "$TMP_CMD_FOLDER/*" $CMD_PATH

sudo chmod +x $CMD_PATH/*

rm -R $TMP_FOLDER
rm $TMP_ZIP
