#!/bin/bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "/usr/bin/unzip"

GITHUB_URL="https://github.com/gadget1999/linux/archive/master.zip"
TMP_ZIP=/tmp/master.zip
TMP_FOLDER=/tmp/linux-master
TMP_CMD_FOLDER=/tmp/linux-master/scripts
CMD_LIB=$CMD_PATH/lib

cd /tmp

rm $TMP_ZIP 2> /dev/null
wget -q $GITHUB_URL
if [ ! -f $TMP_ZIP ]; then
 log_error "Cannot find downloaded file $TMP_ZIP. Internet or github down?"
 exit 1
fi

unzip -qq -o $TMP_ZIP

if !(copy_file $TMP_CMD_FOLDER/update-cmds $CMD_PATH/update-cmds); then
 log "update-cmds was updated, >>>>>> restarting <<<<<<"
 $CMD_PATH/update-cmds
 exit 0
fi

copy_files "$TMP_CMD_FOLDER/*" $CMD_PATH

[ ! -d $CMD_LIB ] && $SUDO mkdir $CMD_LIB
copy_files "$TMP_CMD_FOLDER/lib/*" $CMD_LIB

if [ -x "$(command -v /usr/bin/pwsh)" ]; then
 CMD_AZURE=$CMD_PATH/azure
 # only copy scripts when Azure PowerShell is installed
 [ ! -d $CMD_AZURE ] && $SUDO mkdir $CMD_AZURE
 copy_files "$TMP_CMD_FOLDER/azure/*.ps1" $CMD_AZURE
fi

if [ -x "$(command -v /usr/bin/adb)" ]; then
 # only copy scripts when Android ADB is installed
 copy_files "$TMP_CMD_FOLDER/android/*" $CMD_PATH
fi

$SUDO chmod +x $CMD_PATH/*

rm -R $TMP_FOLDER
rm $TMP_ZIP
