#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

function update_os_debian() {
 debug "Updating APT catalog..."
 sudo apt-get update
 debug "Update system"
 sudo apt-get -y dist-upgrade
 debug "Remove packages no longer needed" 
 sudo apt-get -y autoremove
 debug "Remove packages from cache"
 sudo apt-get -y autoclean
}

function update_os_centos() {
 sudo yum -y update
}

function update_os_entware() {
 opkg update
 opkg upgrade
}

check_os_type

case $OS_TYPE in
 debian)
  log "Update system (Debian)"
  update_os_debian
  ;;
 centos)
  log "Update system (CentOS)"
  update_os_centos
  ;;
 entware)
  log "Update system (Entware)"
  update_os_entware
  ;;
 *)
  log_error "Unknown system type"
  exit 1
  ;;
esac

[ "$1" == "reboot" ] && sudo reboot
