#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

function update_os_debian() {
 $SUDO apt-get update
 $SUDO apt-get -y dist-upgrade
 $SUDO apt-get -y autoremove
}

function update_os_centos() {
 $SUDO yum -y update
}

function update_os_entware() {
 opkg update
 opkg upgrade
}

check_os_type

case $OS_TYPE in
 debian)
  log "Update system (Debian)"
  update_os_debian
  ;;
 centos)
  log "Update system (CentOS)"
  update_os_centos
  ;;
 entware)
  log "Update system (Entware)"
  update_os_entware
  ;;
 *)
  log_error "Unknown system type"
  exit 1
  ;;
esac

[ "$1" == "reboot" ] && $SUDO reboot
