#!/bin/bash

NOW=$(date +"%Y.%m.%d-%H:%M:%S")
PROGRAM="${0##*/}"
LOG=/tmp/$PROGRAM.log
DEBUG=1

source common.sh

INTERNET_STATE="down"

function check_internet() {
 /usr/bin/wget -q --spider http://google.com
 if [ $? -eq 0 ]; then
  debug "Internet is up."
  INTERNET_STATE="up"
 else
  debug "Internet is down."
  INTERNET_STATE="down"
 fi
}

check_internet
while [ "$INTERNET_STATE" != "up" ]
do
 sleep 10
 check_internet
done
