#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh
source $CMD_PATH/lib/certificate.sh

[ $# != 2 ] && show_usage "port path"

check_env "DDNS_DOMAIN CERT_ROOT"

PORT=$1
ROOT_FOLDER=$2

# create TLS cert
check_cert_env

cd $ROOT_FOLDER
$SUDO python3 $CMD_PATH/python/web-server.py \
 $ROOT_FOLDER \
 $PORT \
 --cert_file $CERT_ROOT/$CERT_FULLCHAIN \
 --key_file $WEB_SERVER_KEY
