#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_packages "python3"
check_env "SENDGRID_API_KEY MONITOR_CONFIG"

lock

export SENDGRID_API_KEY

[ "$1" == "debug" ] && export DEBUG
python3 $CMD_PATH/python/web-monitor.py $MONITOR_CONFIG
