#!/usr/bin/env bash

CMD_PATH=$(dirname "$0")
source $CMD_PATH/lib/common.sh

check_env "HOST_DOWNLOAD_ROOT"

[ "$1" == "" ] && show_usage "URL [debug]"

URL=$1

CMD=/usr/local/bin/youtube-dl
if [ ! -x "$(command -v $CMD)" ]; then
 debug "Install youtube-dl"
 sudo pip3 install youtube-dl
fi

TARGET="$HOST_DOWNLOAD_ROOT/Youtube"
[ ! -d $TARGET ] && mkdir -p $TARGET
[ ! -d $TARGET ] && fatal_error "Failed to create folder: $TARGET"
cd $TARGET

[ "$DOWNLOAD_SPEED_LIMIT" != "" ] && CMD="$CMD -r $DOWNLOAD_SPEED_LIMIT"

if [ "$2" == "debug" ]; then
 debug "Update youtube-dl"
 sudo pip3 install --upgrade youtube_dl
 $CMD -v $URL
else
 $CMD $URL
fi
